### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Hierofantus** [UnTraDe/terraria-autoswing#1]
Since the 1.4.1.1. update it doesn't work anymore :(

**Comment by UnTraDe** [comment]
Hi, I've updated it to work with 1.4.1.1 :)
You can download the latest from the releases tab.

**Comment by Hierofantus** [comment]
> Hi, I've updated it to work with 1.4.1.1 :)
> You can download the latest from the releases tab.

Works like charm again! Thank you so much!

**Comment by UnTraDe** [comment]
No problem, thanks for reporting!
