### ISSUE TITLE
Stopped working since latest update

### ISSUE THREAD

**Issue by Hierofantus** [UnTraDe/terraria-autoswing#2]
Hi again!

I wanted to get back to Terraria but your wonderful tool doesn't work since the last update (1.4.2.1.) :(

I also noticed something while using this tool for a long time now. When you start to attack (and you hold left click) and it's on the right side of the monitor, even if you move your pointer to the left side, your character is swinging/attacking to the right side. Would it be possible to change that so you would autoattack depending on the position of the cursor while holding?

Kind regards!

**Comment by UnTraDe** [comment]
Updated to 1.4.2.3 :)

**Comment by Hierofantus** [comment]
Thank you!
